oldboyProject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from bbs import views
from web_chat import urls as chat_urls
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chat/', include(chat_urls)),
    url(r'^$', views.index,name='index'),
    url(r'^category/(\d+)/$',views.category,name="Category"),
    url(r'^article_detail/(\d+)/$',views.articl_detail,name="article_detail"),
    url(r'^new_article/$',views.new_article,name="new_article"),
    url(r'^logout/$',views.acc_logout,name="logout"),
    url(r'^login/$',views.acc_login,name="login"),
    url(r'^post_comment/$',views.post_comment,name="post_comment"),
    url(r'^test/$',views.test),
    url(r'^user_list/$',views.user_list),
    url(r'^get_comments/(\d+)/$',views.get_comments,name='get_comments'),
    # url(r'^get_latest_article_count',views.get_latest_article_count,name='get_latest_article_count'),



]

web_chat/urls.py
from django.conf.urls import url,include

import views
urlpatterns = [

    url(r'dashboard/', views.dashboard,name='chat'),
    url(r'load_contact_list/', views.load_contact_list,name='load_contact_list'),
    url(r'send_msg/', views.send_msg,name='send_msg'),
    url(r'get_msg/', views.send_msg,name='get_msg'),
    url(r'file_upload/', views.file_upload,name='file_upload'),
    url(r'file_upload_progess/', views.file_upload_progess,name='file_upload_progess'),
    url(r'DelFileCache/', views.DelFileCache,name='DelFileCache'),



]

bbs/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models




# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=255,unique=True)
    category = models.ForeignKey('Category')
    priority = models.IntegerField(default=1000)
    author = models.ForeignKey("UserProfile")
    content = models.TextField(max_length=100000)
    breif = models.TextField(max_length=512,default='none.....')
    head_img = models.ImageField(upload_to="upload/")
    publish_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey('Article')
    parent_comment = models.ForeignKey('Comment', blank=True, null=True, related_name='p_comment')
    user = models.ForeignKey('UserProfile')
    comment = models.TextField(max_length=1024)
    date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.comment

class ThumbUp(models.Model):
    article = models.ForeignKey('Article')
    user = models.ForeignKey('UserProfile')

    def __unicode__(self):
        return self.user

class Category(models.Model): #板块
    name = models.CharField(max_length=64,unique=True)
    admin = models.ManyToManyField('UserProfile')

    def __unicode__(self):
        return self.name


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=32)
    groups = models.ManyToManyField('UserGroup')
    friends = models.ManyToManyField('self',related_name='my_friends')

    def __unicode__(self):
        return self.name

###########一对多的实验题
class UserGroup(models.Model):
    name = models.CharField(max_length=64,unique=True)

    def __unicode__(self):
        return self.name

################################分页功能

class user_list(models.Model):
    user_name=models.CharField(max_length=22)
    age=models.IntegerField()

templates/article_detail.html
{% extends 'index.html' %}
{% load xx %}
{% block page-container %}
    {% get_url_parse request.get_full_path %}
    <div class="article-detail"><i class="glyphicon glyphicon-menu-down" aria-hidden="true"></i>
        <h1>{{ articles.title }}</h1><span class="glyphicon glyphicon-menu-down" aria-hidden="true">123</span>
        <div class="article-detail-author">
            <h4>作者：{{ articles.author }}</h4>
            <span>{{ articles.publish_date }}</span><i class="glyphicon glyphicon-comment"></i>{{ articles.comment_set.all.count }}
        </div>
        <hr>
        <img src="{{ articles.head_img }}" alt="">
        <p>{{ articles.content|safe }}</p>

    <span class="pull-right">HOHOHO</span>
        <hr style="margin-top:17px">
    </div>
    <div>
        <div class="hot-comment">发表评论</div>
        {% if  request.user.is_authenticated  %}
            <textarea class="form-control" cols="30" rows="3"></textarea>
            <button type="button" id='button1' class="btn btn-primary pull-right button1">发表</button>
        {% else %}
            <div class="jumbotron">
                <h4 class="text-center"><a  class="btn-link" href="{% url 'login' %}?next={{ request.path }}">登录</a>后评论</h4>
            </div>
        {% endif %}
    </div>
        <hr style="margin-top:57px">
        <div  style="margin-top: 10px" class="hot-comment">热评</div>
        <hr>
        <div class="comment-detail">
            {{ articles.comment_set.select_related.values}}
{#            {% content_tag articles.comment_set.select_related %}#}

{#        这个就是load一个自定义的tag来加载评论#}
        </div>


{% endblock %}

{% block scrpit_block %}
    <script>
    function GetComments(){
        $.get("{% url 'get_comments' articles.id %}",function(callback){
            console.log(callback)

            $('.comment-detail').html(callback)
        })
    }


    $(document).ready(function(){
{#        GetComments()#}
        $('#button1').click(function(){
            var new_comment = $('textarea').val()
            if ($.trim(new_comment).length < 2){
                alert('评论不能少于5个字')
            }else{
                $.post('{% url 'post_comment' %}',{'article_id':"{{ articles.id }}",'comment':new_comment},
                    function(callback){
{#                    GetComments()#}
                    $('textarea').val('')
                })//end post

            }//end if

        }

        )
    })

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
}
    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
                $.ajaxSetup({
                    beforeSend: function(xhr, settings) {
                        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
    </script>

{% endblock %}

templates/index.html
<!DOCTYPE html>
<!-- saved from url=(0056)http://v3.bootcss.com/examples/navbar-fixed-top/#contact -->
<html lang="zh-CN"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v3.bootcss.com/favicon.ico">

    <title>BBS中文网</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/static/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/navbar-fixed-top.css" rel="stylesheet">
    <link href="/static/css/common.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/static/css/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block js_head %}
    {% endblock %}
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'index' %}">天涯社区{{ MEDIA_URL }}</a></li>
            <li><a href="{% url 'Category' 1%}">综合区</a></li>
            <li><a href="{% url 'Category' 2%}">欧美区</a></li>
            <li><a href="{% url 'Category' 3%}">日韩专区</a></li>
			<li><a href="{% url 'Category' 4%}">河北专区</a></li>
			<li><a href="{% url 'chat' %}">聊天室</a></li>

          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
                <li class="dropdown">
                  <a href="http://v3.bootcss.com/examples/navbar-fixed-top/#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user.userprofile.name }} <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'new_article' %}">发帖</a></li>

                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Nav header</li>

                    <li><a href={% url 'logout' %}>注销/退出</a></li>
                  </ul>
                </li>
            {% else %}
              <li><a href={% url 'login' %}>注册/登录</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

        <div class="row">
		{% block page-container %}
            <div class="col-md-8 left-content-panel">
                <div class="content-box">
                    <div class="new-article-notify hide">
                        <a href="{{ request.path }}">有<span></span>条新消息</a>
                    </div>
                    {%  for article in articles reversed %}
                        <div article_id="{{ article.id }}" class="article-box row">
                            <div class="article-head-img col-md-3">
                                <img src="{{ article.head_img }}">
                            </div>
                            <div class="article-summary col-md-8">
                                <a href="{% url 'article_detail' article.id %}">{{ article.title }}</a></h3>
                                <div class="article-attr">
                                    <ul class="list-inline">
                                        <li>{{ article.author.name }}</li>
                                        <li>{{ article.publish_date }}</li>
                                        <li>ThumbUp:{{ article.thumbup_set.select_related.count }}</li>
                                        <li>Comments:{{ article.comment_set.select_related.count }}</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <hr>
                    {% endfor %}
                </div>

            </div>
            <div class="col-md-4 right-sdie-bar">
            right
            </div>
		{% endblock %}
        </div>
{#		{{ request.path }}#}


     <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/css/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="/static/css/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/css/ie10-viewport-bug-workaround.js"></script>
    <script type="text/javascript">
        var menus = $("#navbar a[href='{{ request.path }}']")[0];
{#        var menus = $("#navbar a").attr("href='{{ request.path }}'")#}
{#        console.log(menus)#}
        $(menus).parent().addClass("active");
        $(menus).parent().siblings().removeClass("active");
        console.log("123")
    </script>
    {% block scrpit_block %}
{#        <script>#}
{#            $(document).ready(function () {#}
{#                var new_article_refresh = setInterval(function () {#}
{#                    var Latest_article_id = $($('.content-box').children()[1]).attr('article_id')#}
{#                    console.log(Latest_article_id)#}
{#                    $.getJSON("{% url 'get_latest_article_count' %}",{latest_id:Latest_article_id},function(callback){#}
{#                        console.log(callback)#}
{#                        if(callback.new_article_count > 0){#}
{#                            $('.new-article-notify').removeClass('hide')#}
{#                            $('.new-article-notify span').html(callback.new_article_count)#}
{#                        }#}
{#                    })#}
{#                }, 3000)#}
{#            })#}
{#        </script>#}

    {% endblock %}

templates/login.html
{% extends 'index.html' %}
{% block page-container %}
    <div class="col-md-4">
        <form class="form-signin" action="" method="post">{% csrf_token %}
            <h2 class="form-signin-heading">Please sign in</h2>
            <label for="inputEmail" class="sr-only">用户名</label>
            <input type="text" id="" name="username" class="form-control" placeholder="Username" required="" autofocus="">
            <label for="inputPassword" class="sr-only">密码</label>
            <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required="">
            <div class="checkbox">
              <label>
                <input type="checkbox" value="remember-me"> Remember me
              </label>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
            <p style="color: #c9302c">{{ error_msg }}</p>
        </form>
    </div>
{% endblock %}

templates/new_article.html
{% extends 'index.html' %}
{% block js_head %}
    <script src="/static/ckeditor/ckeditor.js"></script>
{% endblock %}
{% block page-container %}
    <div>
        {% if new_article_obj %}
            <h2>文章{{ new_article_obj.title }}已发表，<a href="{% url 'article_detail' new_article_obj.id %}">点击查看</a></h2>
        {% else %}
            <form enctype="multipart/form-data" class="form-signin" action="{% url 'new_article' %}" method="post">{% csrf_token %}
            <input type="text" name="title" class="form-control" placeholder="文章标题">

            <select name="category_id" class="form-control">
                {% for category in category_list %}
                    <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
            </select>
            <input type="text" name="summary" class="form-control" placeholder="文章概要">
            <input type="file" name="head_img">图片
            <textarea id="ckedit" name="content" ></textarea>
             <br>
            <input type="submit" class="pull-right">

        </form>
        {% endif %}
    </div>
{% endblock %}
{% block scrpit_block %}
    <script >
        CKEDITOR.replace('ckedit')

    </script>
{% endblock %}

templates/user_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table>

    {% for i in user_list %}
        <tr>
            <td>{{ i.user_name }}</td>
            <td>{{ i.age }}</td>
        </tr>
    {% endfor %}


</table>



</body>
</html>